### ISSUE TITLE
Functionality: Moving and Scaling

### ISSUE THREAD

**Issue by eloign** [ilyasm0919/Geometry#2]
current release is not able to do such operations as moving and scaling which is pretty bad for the app connected with inspecting and analyzing shapes and so on :)

**Comment by ilyasm0919** [comment]
Implemented in [469bd4497b2080a8fe405d9cc35f97a3a9cd1320](https://github.com/ilyasm0919/Geometry/commit/469bd4497b2080a8fe405d9cc35f97a3a9cd1320)
