### ISSUE TITLE
Look and Feel: Size of Angles

### ISSUE THREAD

**Issue by eloign** [ilyasm0919/Geometry#3]
angle(A, B, C) is too big on the canvas, I think it would be better to add so-called scaling factor as a fourth argument to a construction, for example: angle(A, B, C, 0.5)

**Comment by ilyasm0919** [comment]
That is not good idea.
Firstly, scaling factor is absolutely useless on intermediate angles (for example, when you draw bisector).
Secondly, we don't have angle(A, B, C), we have angle(Angle). Yes, we can add scaling factor as fourth parameter when parsing Angle by three Points, but that would be a little strange.

Much better would be add modifier like `[size(0.5)]`.
That requires a little different way of parsing modifiers: when word is `size` we must parse parens and number between them and return from `parseModifier` immeddiately.

**Comment by ilyasm0919** [comment]
Fixed in #6
