### ISSUE TITLE
Look and Feel: Lines and Points

### ISSUE THREAD

**Issue by eloign** [ilyasm0919/Geometry#4]
When things are being painted on the canvas, points are painted first (as it seems, because they are commonly specified earlier in the corresponding code) and that's a problem, because they are painted under lines, which seems (to me) to look ugly

**Comment by ilyasm0919** [comment]
Fixed in [66e43b03324a8acccb614bc897bfc3ee1c881ab6](https://github.com/ilyasm0919/Geometry/commit/66e43b03324a8acccb614bc897bfc3ee1c881ab6)
