### ISSUE TITLE
A segment with multiple points

### ISSUE THREAD

**Issue by GrafGeometr** [ilyasm0919/Geometry#9]
When you draw in GeoGebra, you try to hide lines or replace them with segments (to show that several points lie on the same line), because lines clutter the drawing a lot. In the app it is possible to draw points without drawing lines. This is good, but in order to show that 3 or more points lie on the same line you need to connect them with segments somehow. At the same time, I would like the segment to cover them all regardless of the location of these points. I would like to see some function like `multisegment(P_1, P_2, ...)` that draws such a segment.

**Comment by ilyasm0919** [comment]
We already have a function with behavior like `multisegment` - it is `polygon`: in case of collinear points it will look like a segment from the first point to the last one. But this may not be the right way to do it.

If another function (`multisegment`) is needed for this, what should it do in the case of non-collinear points? Should it return the diameter of the polygon?

I think a good solution could be a line modifier (like `[bounded]`) that changes the way the line is drawn, from the first point on it to the last. Perhaps this should be the default behavior for lines that have at least two points on them (and then we would need a modifier like `[unbounded]`).

**Comment by GrafGeometr** [comment]
I think that the `[unbounded]` modifier is a good idea. So if I write code like this:

```
A, B, C, D - are moveable points
T = intersect(A, B, C, D) 
[unbounded] line(A, B) 
line(C, D)
```

Line with points A, B, T will be displayed as a normal line, and line with points C, D, T will be bounded.
